import type { NextPage } from 'next'
import Head from 'next/head'
import Home from './home'
import Image from 'next/image'

import indexStyles from '../styles/Index.module.css'

const Index: NextPage = () => {
  return (
    <div className={indexStyles.container}>
      <Head>
        <title>Decentralised Society</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home></Home>
    </div>
  )
}

export default Index