import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'

import Navbar from './navbar'
import Home from './home'
import About from './about'
import Events from './events'

import styles from '../styles/Index.module.css'
import Footer from './footer'

const Index: NextPage = () => {

  // let topbutton: HTMLElement | null;

  // useEffect(() => {
  //   topbutton = document.getElementById("topBtn");

  //   window.onscroll = () => {
  //     if (topbutton)
  //     if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
  //       topbutton.style.display = "block";
  //     } else {
  //       topbutton.style.display = "none";
  //     }
  //   }  
  // })

  // function topFunction() {
  //   document.body.scrollTop = 0; // for Safari
  //   document.documentElement.scrollTop = 0; // for others
  // }

  return (
    <div className={styles.container}>
      <Head>
        <title>Decentralised Society</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <div className={styles.bodyWrapper}>
        {/* <button onClick={topFunction} className={styles.topBtn}>TOP</button> */}

        <Home></Home>
        <Events></Events>
        <About></About>
      </div>
      <Footer></Footer>
    </div>
  )
}

export default Index