import type { NextPage } from 'next'
import Head from 'next/head'

import Navbar from './navbar'
import Home from './home'
import About from './about'
import Events from './events'


import Image from 'next/image'
import indexStyles from '../styles/Index.module.css'
import { useState } from 'react'
import SmoothScroll from 'smooth-scroll'
import Footer from './footer'
// import { Navbar } from '@mantine/core'

// const smoothScroll = new SmoothScroll();

// window.smoothScroll = smoothScroll;

// const scrollTo = (val: any) => {
//   smoothScroll.animateScroll(val);
// }

// window._scrollTo = (val: any) => {
//   smoothScroll.animateScroll(val);
// }

// window._scrollToElement = (el: string) => {
//   const element: HTMLElement | null = document.getElementById(el);

//   if (element) {
//     scrollTo(element.getBoundingClientRect().top - window.innerHeight / 8 + window.scrollY)
//   }
// }


const Index: NextPage = () => {
  return (
    <div className={indexStyles.container}>
      <Head>
        <title>Decentralised Society</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <div className={indexStyles["body-wrapper"]}>
        <Home></Home>
        <div style={{ maxWidth: '100%', padding: '0 8vw' }}>
          <About></About>
          <Events></Events>
        </div>
        <Footer></Footer>
      </div>
    </div>
  )
}

export default Index